repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: local
  hooks:
  - id: ruff-format
    name: ruff-format
    entry: ruff format
    language: system
    pass_filenames: true
    types_or: [python]

  - id: ruff-check
    name: ruff-check
    entry: ruff check
    language: system
    pass_filenames: true
    types_or: [python]

  - id: pytest
    name: pytest
    entry: shell/pytest.sh
    language: system
    pass_filenames: false
    always_run: true
    args: [-vvv]

  - id: mypy
    name: mypy
    entry: shell/mypy.sh hurrqueue
    language: system
    pass_filenames: false
    types_or: [python]
