version: "3.6"
services:
  postgres:
    image: postgres:alpine
    ports:
    - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
